Awesome Books
SaveryIV/Awesome-Books-Project pull request #1
Opened 2023-07-03 13:32 UTC by SaveryIV

In this project I have been working on the:

- Local Storage(functioning).
- Add, delete, and show the cards for each book(checked).
- Saving the data on an array of objects(books) using the constructor function(checked).

2023-07-03 14:02 UTC, V-Blaze requested changes
Hi @ , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![dcentl8-9b96e129-9725-401b-ac34-2feb990202a0](https://user-images.githubusercontent.com/107632780/229646232-19bbafea-ca96-4b36-ad5d-1d64c00d667c.gif)

## Invalid Code Review Request

## You have submitted a project, that doesn't have commits from your partner. this is a pair programming activity and your partner needs to contribute and commit to the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-03 14:06 UTC, souad988 reviewed
Hi @SaveryIV , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't include commits from your partner , kindly as suggested by the previous reviewer contact your partner to do their part of work and if you still have problems reach out to the students success team using the button in your dashboard then copy their response in this PR summary so the next reviewer can proceed with the review 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-04 12:34 UTC, topeogunleye requested changes
Hi @SaveryIV, @noelfoka, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
👍 You have implemented a basic UI with plain HTML and added some style to make it look nice.
👍 You have used an array of objects to store the books collection and displayed it on the page.
👍 You have created functions to add and remove books from the collection and updated the UI accordingly.
👍 You have used localStorage to preserve the data in the browser's memory and confirmed it by reloading the page.
👍 You have used plain JavaScript for the main functionality of the app and followed the ESLint rules.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 12:34 UTC, topeogunleye commented on app.js
> +}
Hi @SaveryIV,

Great job on your code! I noticed that you used the `splice()` method to remove an element from the array. However, the project requirement states that students can use the `filter()` method to remove a book from the collection. The `filter()` method creates a new array with all elements that pass the test implemented by the provided function. Here is an example of how it can be implemented:

```javascript
const books = [];

const removeBook = (bookID) => {
  // bookID can be any other property, e.g. title or author, in as much it is unique
  books = books.filter(({ id }) => bookID !== id); // This assumes that `bookID` parameter is the book id
  localStorage.setItem('books', JSON.stringify(books));
}

2023-07-04 12:34 UTC, topeogunleye commented on README.md
> +Feel free to check the [issues page](../../issues/).
- [ ] [OPTIONAL] I kindly suggest that you change the link here to the correct link for your issues page which is `https://github.com/SaveryIV/Awesome-Books-Project/issues`

2023-07-05 09:47 UTC, aamirkhan2478 approved these changes
Hi @SaveryIV, 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly :+1: 
✅ No linter error :+1: 
✅ Good commit messages :+1: 
✅ Good descriptive PR :+1: 
✅ Well done :clap: you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 09:50 UTC, merged

2023-07-11 09:47 UTC, rotimiazeez reviewed
# Hi @SaveryIV 👋🏽,

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a PR that is already merged. Kindly ensure the PR you are submitting for review is always open with the changes made present so CRs can perform a proper review on it 😉

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._